[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18", VITE_STRIPE_PUBLISHABLE_KEY = "pk_test_51OqXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Add security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-eval' https://js.stripe.com; connect-src 'self' https://*.firebaseio.com https://*.cloudfunctions.net wss://*.firebaseio.com https://*.netlify.app https://api.stripe.com; frame-src https://js.stripe.com;"